name: release
on:
  push:
    branches:
      - main
jobs:
  call-build-lint-test-workflow:
    uses: ./.github/workflows/build-lint-test.yml
  deploy-package:
    runs-on: ubuntu-latest
    needs: [call-build-lint-test-workflow]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: yarn install --frozen-lockfile
      - name: generate
        run: cd packages/module && yarn generate
      - name: Build dist
        run: yarn build
      - name: Release to NPM
        run: cd packages/module && npx semantic-release@19.0.5
